### ISSUE TITLE
Providing alternative functions for string manipulation functions

### ISSUE THREAD

**Issue by n2029-ndensan** [dverite/icu_ext#13]
Please provide an alternative function to the following character string operation function.

char_length|character_length|substring|trim|btrim|left
|lpad|ltrim|regexp_match|regexp_matches
|regexp_replace|regexp_split_to_array|regexp_split_to_table
|replace|reverse|right|rpad|rtrim|split_part|strpos|substr|starts_with

**Comment by dverite** [comment]
> char_length|character_length|substring|trim|btrim|left|lpad|ltrim|
> |replace|reverse|right|rpad|rtrim|split_part|substr|
 
If there were ICU alternatives to these functions, I don't see how they would differ.

> regexp_match|regexp_matches|regexp_replace|regexp_split_to_array|regexp_split_to_table

ICU provides regular expressions
https://unicode-org.github.io/icu/userguide/strings/regexp.html
This might be exposed in icu_ext in the future, for some Unicode features that Postgres core doesn't necessarily have, such as `\p{UnicodeProperty}`

> strpos|starts_with

The locale-aware `icu_strpos()` already exists. `starts_with(s1,s2)` is equivalent to `icu_strpos(s1,s2, locale)==1`

**Comment by n2029-ndensan** [comment]
In these functions,
Even if there are variant character selectors and combining characters, it is necessary to be able to correctly judge one character.
It is necessary to take measures so that the data is not separated between the base character and the variant character selector.
It is easy to handle if it is provided in the form of argument and return value of the same function as postgresql.

![image](https://user-images.githubusercontent.com/74336846/172078333-30229a5c-e960-4207-b71f-0674c738b32a.png)

### 1. char_length => icu_char_length
### 2. character_length => icu_character_length

\# select char_length(U&'\+00304B' || U&'\+00309A' || U&'\+00304D') ;
 char_length
\-------------
           3

I expect length 2.

\# select icu_char_length(U&'\+00304B' || U&'\+00309A' || U&'\+00304D') ;
 icu_char_length
\-------------
           2


### 3. substring => icu_substring

\# select substring(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' from 1 for 1) ;
 substring
\-----------
 か

This return U&'\+00304B'.
I expect U&'\+00304B' || U&'\+00309A'.

\# select icu_substring(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' from 1 for 1) ;
 icu_substring
\-----------
 か゚


### 4. trim => icu_trim

\# select trim(both U&'\+00304B' from concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D') );
 btrim
\-------
 ゚き

This return U&'\+00309A' || U&'\+00304D'.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_trim(both U&'\+00304B' from concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D') );
 icu_trim
\-------
 か゚き


### 5. btrim => icu_btrim

\# select btrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B' );
 btrim
\-------
 ゚き

This return U&'\+00309A' || U&'\+00304D'.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_btrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B' );
 icu_btrim
\-------
 か゚き


### 6. left => icu_left

\# select left(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),1);
 left
\------
 か

This return U&'\+00304B'.
I expect U&'\+00304B' || U&'\+00309A'.

\# select icu_left(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),1);
 icu_left
\------
  か゚


### 7. lpad => icu_lpad

\# select lpad(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),4,'0');
 lpad
\-------
 0か゚き

This return  '0' || U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.
I expect '00' || U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_lpad(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),4,'0');
 icu_lpad
\-------
 00か゚き


### 8. ltrim => icu_ltrim

\# select ltrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 ltrim
\-------
 ゚き

This return U&'\+00309A' || U&'\+00304D'.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_ltrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 icu_ltrim
\-------
 か゚き


### 9. regexp_match => icu_regexp_match

\# select regexp_match(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 regexp_match
\--------------
 {か}

This return U&'\+00304B'.
I expect as follows.

\# select icu_regexp_match(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 regexp_match
\--------------

(1 行)


### 10. regexp_matches => icu_regexp_matches

\# select regexp_matches(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 regexp_matches
\----------------
 {か}
(1 行)

This return U&'\+00304B'.
I expect as follows.

\# select regexp_matches(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304a');
 regexp_matches
\----------------
(0 行)


### 11. regexp_replace => icu_regexp_replace

\# select regexp_replace(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B','0');
 regexp_replace
\----------------
 0゚き

This return '0' || U&'\+00309A' || U&'\+00304D'.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_regexp_replace(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B','0');
 icu_regexp_replace
\----------------
 か゚き


### 12. regexp_split_to_array => icu_regexp_split_to_array

\# select regexp_split_to_array(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 regexp_split_to_array
\-----------------------
 {"",゚き}
(1 行)

This return {'', U&'\+00309A' || U&'\+00304D'}.
I expect {U&'\+00304B' || U&'\+00309A' || U&'\+00304D'}.

\# select icu_regexp_split_to_array(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 icu_regexp_split_to_array
\-----------------------
 {か゚き}
(1 行)


### 13. regexp_split_to_table => icu_regexp_split_to_table

\# select regexp_split_to_table(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 regexp_split_to_table
\-----------------------

 ゚き
(2 行)

This return '' and U&'\+00309A' || U&'\+00304D'}.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_regexp_split_to_table(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B');
 icu_regexp_split_to_table
\-----------------------
 か゚き
(1 行)


### 14. replace => icu_replace

\# select replace(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B','0');
 replace
\---------
 0゚き
(1 行)

This return '0' || U&'\+00309A' || U&'\+00304D'.
I expect U&'\+00304B' || U&'\+00309A' || U&'\+00304D'.

\# select icu_replace(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),U&'\+00304B','0');
 icu_replace
\---------
 か゚き
(1 行)


### 15. reverse => icu_reverse

\# select reverse(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'));
 reverse
\---------
 き゚か
(1 行)

This return U&'\+00304D' || U&'\+00309A' || U&'\+00304B'.
I expect  U&'\+00304D' || U&'\+00304B' || U&'\+00309A'.

\# select icu_reverse(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'));
 icu_reverse
\---------
 きか゚
(1 行)


### 16. right => icu_right

\# select right(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),2);
 right
\-------
 ゚き
(1 行)

This return  U&'\+00309A' || U&'\+00304D'.
I expect  U&'\+00304B' || U&'\+00309A' ||  U&'\+00304D'.

\# select icu_right(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),2);
 icu_right
\-------
 か゚き
(1 行)


### 17. rpad => icu_rpad

\# select rpad(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),4,'0');
 rpad
\-------
 か゚き0
(1 行)

This return  U&'\+00304B' || U&'\+00309A' ||  U&'\+00304D' || '0'.
I expect  U&'\+00304B' || U&'\+00309A' ||  U&'\+00304D' || '00'.

\# select icu_rpad(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D'),4,'0');
 icu_rpad
\-------
 か゚き00
(1 行)


### 18. rtrim => icu_rtrim

\# select rtrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D' ||  U&'\+00309A');
 rtrim
\-------
 か
(1 行)

This return  U&'\+00304B'.
I expect  U&'\+00304B' || U&'\+00309A'.

\# select icu_rtrim(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D' ||  U&'\+00309A');
 icu_rtrim
\-------
 か゚
(1 行)


### 19. split_part => icu_split_part

\# select split_part(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D' ||  U&'\+00309A',2);
 split_part
\------------

(1 行)
\# select split_part(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D',2);
 split_part
\------------
 ゚
(1 行)

This return  U&'\+00309A'.
I expect  as follows.

\# select icu_split_part(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D',1);
 icu_split_part
\------------
 か゚き
(1 行)
\# select icu_split_part(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304D',2);
 icu_split_part
\------------

(1 行)


### 20. strpos => icu_strpos

Already exists.


### 21. substr => icu_substr

\# select substr(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),1,1);
 substr
\--------
 か
(1 行)

This return  U&'\+00304B'.
I expect  U&'\+00304B' || U&'\+00309A' .

\# select icu_substr(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),1,1);
 icu_substr
\--------
 か゚
(1 行)


### 22. starts_with => icu_starts_with

\# select starts_with(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304B');
 starts_with
\-------------
 t
(1 行)

This return  true.
I expect  false.

\# select icu_starts_with(concat(U&'\+00304B' || U&'\+00309A' || U&'\+00304D' ||  U&'\+00309A'),U&'\+00304B');
 icu_starts_with
\-------------
 f
(1 行)
