### ISSUE TITLE
Usage on client side

### ISSUE THREAD

**Issue by markmaker** [dverite/icu_ext#17]
Hi,

is there an easy way to use these functions on the client side, from C/C++ code (short of pilfering the function's code)?

Background: for various reasons we need to make sure that the client compares and sorts strings the same way as the data base (which uses an ICU collation).

Thanks,
Mark

**Comment by dverite** [comment]
For a client-side project, I don't see much prospect of reusing code from that extension. There are too many calls to Postgres macros and functions that are not needed in a standalone application.
