### ISSUE TITLE
header file included twice in many places.

### ISSUE THREAD

**Issue by jianhe-fun** [dverite/icu_ext#19]
just found out the small issue:
in icu_date.c
#include "icu_ext.h" inside already include #include "postgres.h" 

aslo
#include "datatype/timestamp.h" inside already include #include "datatype/timestamp.h"

**Comment by dverite** [comment]
Thanks for noticing! I've made the includes a bit more consistent with commit 0161c1c
C files can still include ICU files in common with icu_ext.h but I'm okay with that.
