### ISSUE TITLE
debian/redhat packages

### ISSUE THREAD

**Issue by marco44** [dverite/icu_ext#3]
Do you think there would be a way to have this packaged by PGDG? There are sone very interesting functions not available in core PostgreSQL, like icu_word_boundaries... for asian language, this is invaluable.

Thanks

**Comment by dverite** [comment]
I guess I should ask to the pgdg maintainers if they're interested. I'll email the team through the Debian Maintainers address. Technically I don't think there would be any difficulty, since the only dependency is with the ICU library.

**Comment by df7cb** [comment]
Hi,
as already said in the email, for the package we would need
* releases (github tags)
* a testsuite (likely based on pgxs/pg_regress)

I can take care of the packaging part.

**Comment by dverite** [comment]
Thanks Christoph. I'll add regression tests, tag a release and ping you back soon.

**Comment by df7cb** [comment]
Debian packages have been available for some time via apt.postgresql.org now.

**Comment by marco44** [comment]
Yeah and they work great !
