### ISSUE TITLE
Make error - pgxn install issue with pgdg postgres

### ISSUE THREAD

**Issue by Maxzor** [dverite/icu_ext#7]
Hello,
I have postgres12.2 from pgdg.
I am trying to install icu_ext from pgxn and get an upfront fail :
http://ix.io/2ce8
Maybe I am missing something very dumb?
Best regards

**Comment by Maxzor** [comment]
Pretty trivial, it was about making the include available :
`sudo cp -r /usr/local/pgsql/include/server  /usr/include/postgresql/12/server`
and using the postgres preprocessor macro USE_ICU.

**Comment by dverite** [comment]
Normally you would do `sudo apt install postgresql-server-dev-12`.
USE_ICU is defined in pg_config.h in the server includes
