### ISSUE TITLE
[Feature request] Prefix matching / icu_starts_with()

### ISSUE THREAD

**Issue by noinkling** [dverite/icu_ext#9]
First and foremost, thanks for the great extension.

I'd like to humbly request exposing an optimized prefix match function, i.e. a nondeterministic collation-aware equivalent to `LIKE 'prefix%'`, or the `starts_with()` function introduced in Postgres 11. Essentially `icu_strpos() = 1` except that it short-circuits so it doesn't have to search through the whole string.

Or perhaps, more generically, a version of `icu_strpos()` that allows you to specify the maximum position to search for (the start of) a match (may as well include the minimum position too).

**Comment by dverite** [comment]
I agree that this would be useful. It would perform better for left-anchored pattern matching.
Unfortunately the ICU C API (specifically [usearch](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/usearch_8h.html)) doesn't seem to support this, and I haven't found any way to work around this with ICU.

**Comment by noinkling** [comment]
I did skim over the usearch API before creating this issue, I thought it looked possible, but obviously I didn't look hard enough. Looking at it again more carefully reveals that you're correct, and some posts I found on the ICU mailing list confirm that it would need to be implemented using lower-level APIs.

There's an issue with naively doing `icu_strpos() = 1` too, because you can specify the collation to ignore leading spaces/punctuation/symbols, but ICU [only implements "minimal" match semantics](https://unicode-org.github.io/icu/userguide/collation/string-search.html#icu-string-search-model), meaning the returned start position won't include those ignored characters, as illustrated in the table [here](http://www.unicode.org/reports/tr10/#Matches_Table) (figure 5). In other words `icu_compare('...foo', 'foo', 'und-u-ka-shifted')` says they're the same, but `icu_strpos('...foobar', 'foo', 'und-u-ka-shifted')` returns `4`, not `1`. You would need to do something like:
```pgsql
icu_strpos(str, prefix) > 0 AND
icu_compare(left(str, icu_strpos(str, prefix) - 1 + char_length(prefix)), prefix) = 0

-- or with a nondeterministic collation the second line could be:
left(str, icu_strpos(str, prefix) - 1 + char_length(prefix)) = prefix
```

Luckily that's all kind of irrelevant, since there's an easier way that doesn't even need any extension functions: the U+FFFF character/codepoint is guaranteed to sort higher than any other collation element (when using an ICU collation), so you can just do:
```pgsql
-- Assuming ICU implicit collation:
str BETWEEN prefix AND prefix || U&'\FFFF'

-- or if the inclusive upper bound bothers you:
str >= prefix AND str < prefix || U&'\FFFF'
```
I found a note of it here: https://unicode-org.github.io/icu/userguide/collation/architecture.html#generating-bounds-for-a-sort-key-prefix-matching

This way it can utilize an index to do basically all the work in advance too, and even without one will probably be far more performant than the function approach.

Hopefully this is helpful for anyone else who is looking for this functionality and happens to stumble across this post.

**Comment by dverite** [comment]
I agree that `icu_strpos(..,...)=1` is ineffective with ignorable characters, I forgot about that. BTW I don't think that the double-check you mention even works if the searched strings itself has ignorable characters (i.e. `strpos('...foobar', '..foo', 'und-u-ka-shifted')`)

The trick you're pointing out with U&'\FFFF' is **super interesting**, because if you have a B-Tree index on `str COLLATE "some-non-deterministic collation"`,  Postgres core can use it right now for range-searching with inequality or BETWEEN. It also means that if LIKE with non-deterministic collations is to be implemented in future Postgres versions, that might be the building block to implement `LIKE 'prefix%'`.

**Comment by noinkling** [comment]
An edge case with that trick is that it won't match the string if it also includes U+FFFF, e.g. `U&'prefix\FFFF\FFFF...'`

I don't think there's a way to generate a proper (i.e. exclusive) upper bound without looking at the sort key. I don't know if that's something that makes sense to do internally in Postgres or not.
